{
 "title": "sigma",
 "description": "Simple exporter for cadvisor only",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "Filters" },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Sigma", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"sigma\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"sigma\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"sigma\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"sigma\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}